# Generated by Django 5.2.4 on 2025-07-13 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(verbose_name='Temperatura (°C)')),
                ('sujidade', models.FloatField(verbose_name='Nível de Sujidade (%)')),
                ('sistema_ligado', models.BooleanField(verbose_name='Sistema Ligado?')),
                ('aquecedor_ligado', models.BooleanField(verbose_name='Aquecedor Ligado?')),
                ('emergencia_ativa', models.BooleanField(verbose_name='Emergência Ativa?')),
                ('alerta_sujidade', models.BooleanField(verbose_name='Alerta de Sujidade?')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora da Leitura')),
            ],
            options={
                'verbose_name': 'Dado do Sensor',
                'verbose_name_plural': 'Dados dos Sensores',
                'ordering': ['-timestamp'],
            },
        ),
    ]
