# Generated by Django 5.2.4 on 2025-07-13 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensordata',
            options={},
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='alerta_sujidade',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='aquecedor_ligado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='emergencia_ativa',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sistema_ligado',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='sujidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperatura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
